### ISSUE TITLE
问个问题 ~

### ISSUE THREAD

**Issue by powerfulyang** [ScottWei007/mt5webapi#2]
您好，请问一下
```
#socket
socketserver:
  id: localhost
  port: 28888
```
**28888端口是怎么配置的？**
